[server]
listen = "::"
port = 1234

[proxy]
protocol = "socks"
# protocol_class = "tmmp.protocols.proxy:SocksProxy"

[application]
protocols = [ "tls" ]
# protocols_class = [ "tmmp.protocols.application:TlsProtocol" ]

[tls]
ciphers = "ALL"

[providers]
certificates = "selfsigned"